#!/usr/bin/env bash


##===========================================================##
## AWS PARAMETER STORE
##===========================================================##
if [ ! -z "${AWS_PARAMETER_PATH}" ]; then
    dotenv get-dotenv --path ${AWS_PARAMETER_PATH} --output export -d /etc/profile.d/dotenv
fi

##===========================================================##
## S3_SYNC_PREFIX_SRC && S3_SYNC_FILE_SRC
##===========================================================##
## (example: s3://bucket-name/object-key.txt)
## S3_SYNC_PREFIX_SRC
## Source location of the LIST of files that will be synced down to the container.
## S3_SYNC_FILE_SRC
## Source location of the SINGLE file that will be synced down to the container.
## S3_SYNC_DST
## Destination of where these files should be synced down to. Defaults to /opt/s3-sync

if [ -z "${S3_SYNC_DST}" ]; then
    S3_SYNC_DST=/opt/s3-sync/
fi

if [ ! -z "${S3_SYNC_PREFIX_SRC}" ]; then
    echo "Syncing ${S3_SYNC_PREFIX_SRC} to ${S3_SYNC_DST}"
    aws s3 sync $S3_SYNC_PREFIX_SRC $S3_SYNC_DST
fi

if [ ! -z "${S3_SYNC_FILE_SRC}" ]; then
    echo "Syncing ${S3_SYNC_FILE_SRC} to ${S3_SYNC_DST}"
    aws s3 cp $S3_SYNC_FILE_SRC $S3_SYNC_DST
fi

##===========================================================##
## Environmental Variables
##===========================================================##
## If you add environmental variables to a /etc/profile.d/ file,
## this entrypoint will load them up here. This way you can add
## secrets at run time or with a hook and it will be loaded into 
## the environment

shopt -s nullglob
PROFILE_VARIABLES=(/etc/profile.d/*)
shopt -u nullglob

for f in "${PROFILE_VARIABLES[@]}"
do
    echo "Sourcing ${f}"
    source $f;
done

##===========================================================##
## Hooks with /flipbox.d/
##===========================================================##
## Shell files (bash with .sh extensions) within the /flipbox.d/
## directory will be run.

# Glob files
shopt -s nullglob
HOOKS=(/flipbox.d/*.sh)
shopt -u nullglob

# Loop thru and run
for i in "${HOOKS[@]}"
do
    echo "Running shell script: ${i}"
    bash $i
done

exec "$@"
