#!/usr/bin/env bash


##===========================================================##
## AWS PARAMETER STORE
##===========================================================##
if [ ! -z "${AWS_PARAMETER_PATH}" ]; then
    dotenv get-dotenv --path ${AWS_PARAMETER_PATH} --output export -d /etc/profile.d/dotenv
fi


##===========================================================##
## Hooks with /flipbox.d/
##===========================================================##
## Shell files (bash with .sh extensions) within the /flipbox.d/
## directory will be run.

# Glob files
shopt -s nullglob
HOOKS=(/flipbox.d/*.sh)
shopt -u nullglob

# Loop thru and run
for i in "${HOOKS[@]}"
do
    echo "Running shell script: ${i}"
    bash $i
done

##===========================================================##
## Environmental Variables
##===========================================================##
## If you add environmental variables to a /etc/profile.d/ file,
## this entrypoint will load them up here. This way you can add
## secrets at run time or with a hook and it will be loaded into 
## the environment

shopt -s nullglob
PROFILE_VARIABLES=(/etc/profile.d/*)
shopt -u nullglob

for f in "${PROFILE_VARIABLES[@]}"
do
    echo "Sourcing ${f}"
    source $f;
done

exec "$@"
